### PR TITLE
Support Lighthouse 6

### PR DESCRIPTION
**Pull request by pyrou**

### CODE REVIEW

**Comment by pyrou** [comment]
I was possibly a bit to quick on this PR. 
Due to upgrade of `webonyx/graphql-php` from 14 to 15 in LH6, some classe has changed. 
I'll update code accordingly. It looks complex, nearly impossible, to get something working both on LH 6 and LH 5.

@peterkeijsers Once these changes done, would you accept this PR as a new major version lighthouse-apollo v3 that will also :
- drop support of Lighthouse 5.x
- and so drop support of laravel 6, 7, 8 since Lighthouse 6 doesn't support it anymore
- and so drop support of php 7.x since Laravel 9 doesn't support it anymore

**Comment by peterkeijsers** [comment]
hi @pyrou 

I've not the time right now to investigate the impact of the upgrade myself. But I'm open to a PR and a possible v3 version release that is not backwards compatible with older versions of Lighthouse. Depending on the size of the PR it could take I while before I'm able to test the PR and merge it though.

Thanks for your effort in updating the package!

**Comment by pyrou** [comment]
CI is all green now :) 

I'll test it in our lighthouse based project for the next days, with some "real-life" tracing data.

**Comment by pyrou** [comment]
Hi @peterkeijsers, this is a little reminder for a summer review 🏖️

**Comment by peterkeijsers** [comment]
Hi @pyrou 

Sorry for the delay, but your MR has been merged. Thank you for you effort in updating this package! Much appreciated!

Kind regards,
Peter Keijsers

**Pull request merged**
