### PR TITLE
Support Laravel 10

### PR DESCRIPTION
**Pull request by pyrou**

### CODE REVIEW

**Comment by pyrou** [comment]
ping @MaartenStaa :)

**Comment by MaartenStaa** [comment]
LGTM @pyrou! I don't work at Bright Alley anymore, so unfortunately I can't merge the PR or tag a new release. @peterkeijsers maybe you can help?

**Comment by pyrou** [comment]
ping @peterkeijsers :)

**Comment by peterkeijsers** [comment]
Hi @pyrou

thank you for working on making this package Laravel 10 compatible. I've released v2.5 just now with your commits in it.

**Pull request merged**
